import {
  CanActivate,
  ExecutionContext,
  Injectable,
  Logger,
  UnauthorizedException,
} from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { verifyToken } from '@clerk/backend';
import type { Request } from 'express';
import { IS_PUBLIC_KEY } from './public.decorator.js';

@Injectable()
export class ClerkGuard implements CanActivate {
  private readonly logger = new Logger(ClerkGuard.name);

  constructor(private readonly reflector: Reflector) {}

  /**
   * Comma-separated frontend origins allowed to obtain JWTs for this API.
   * Without this set, ANY Clerk-issued token signed by the same secret can
   * pass — including ones generated by other (potentially attacker-owned)
   * Clerk apps if the secret is ever shared. Wraps as `authorizedParties`
   * on verifyToken.
   */
  private readonly authorizedParties: string[] = (process.env['CLERK_AUTHORIZED_PARTIES'] ?? '')
    .split(',')
    .map((p) => p.trim())
    .filter(Boolean);

  /**
   * Optional Clerk issuer URL (https://<your-instance>.clerk.accounts.dev).
   * Pinning the issuer prevents tokens from a different Clerk instance with
   * the same secret from being accepted.
   */
  private readonly issuer: string | undefined = process.env['CLERK_ISSUER_URL']?.trim();

  async canActivate(context: ExecutionContext): Promise<boolean> {
    // Bypass auth entirely for routes marked with @Public(). This is used by
    // the unauthenticated /health endpoint that Render's health checks and
    // the UptimeRobot keep-alive pinger hit every 5 minutes.
    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);
    if (isPublic) {
      return true;
    }

    const request = context.switchToHttp().getRequest<Request>();
    const authHeader = request.headers['authorization'];

    if (!authHeader?.startsWith('Bearer ')) {
      throw new UnauthorizedException('Missing or invalid Authorization header');
    }

    const token = authHeader.slice(7);
    const secretKey = process.env['CLERK_SECRET_KEY'];

    if (!secretKey) {
      throw new UnauthorizedException('Server auth configuration error');
    }

    try {
      const payload = await verifyToken(token, {
        secretKey,
        // Both are optional in @clerk/backend's verifyToken. We pass them
        // when configured; warn loudly if not, since unbounded acceptance
        // is a real risk.
        ...(this.authorizedParties.length > 0 && { authorizedParties: this.authorizedParties }),
        ...(this.issuer && { issuer: this.issuer }),
      });
      (request as Request & { user: typeof payload }).user = payload;
      return true;
    } catch (err) {
      this.logger.warn(`verifyToken rejected: ${(err as Error).message}`);
      throw new UnauthorizedException('Invalid or expired token');
    }
  }
}
